// Central UI string table with English + Hindi. Pose content stays English for
// now; UI labels switch with the language setting.
import { getSetting } from './settings.js';

const en = {
  appName: 'kaya haus',
  productName: 'Yoga Adventure Wheel',
  tagline: 'Spin the wheel, strike a pose!',
  tapToBegin: 'Tap to begin',
  play: 'Play',
  start: 'Start',
  home: 'Home',
  back: 'Back',
  next: 'Next',
  done: 'Done',
  cancel: 'Cancel',
  save: 'Save',
  close: 'Close',
  howToPlay: 'How to Play',
  chooseMode: 'Choose an Adventure',
  choosePlayers: 'Who is playing?',
  spin: 'Spin the Wheel!',
  spinning: 'Spinning…',
  getReady: 'Get ready',
  holdPose: 'Hold the pose!',
  startPose: "I'm ready — start!",
  pass: 'Great job! ⭐',
  needsPractice: "Let's practice 💪",
  monitorPrompt: 'Grown-up: how did that go?',
  celebrate: 'Woohoo!',
  encourage: 'Nice try — keep going!',
  results: 'Results',
  playAgain: 'Play Again',
  pause: 'Pause',
  resume: 'Resume',
  quit: 'Quit Game',
  leaderboard: 'Leaderboard',
  achievements: 'Achievements',
  statistics: 'Statistics',
  settings: 'Settings',
  admin: 'Grown-Up Zone',
  poseLibrary: 'Pose Library',
  players: 'Players',
  wheelBuilder: 'Wheel Builder',
  backup: 'Backup & Restore',
  funFact: 'Fun Fact',
  benefits: 'Good For',
  safety: 'Safety First',
};

const hi = {
  appName: 'kaya haus',
  productName: 'योग एडवेंचर व्हील',
  tagline: 'पहिया घुमाओ, आसन बनाओ!',
  tapToBegin: 'शुरू करने के लिए टैप करें',
  play: 'खेलें',
  start: 'शुरू',
  home: 'होम',
  back: 'वापस',
  next: 'आगे',
  done: 'हो गया',
  cancel: 'रद्द करें',
  save: 'सहेजें',
  close: 'बंद करें',
  howToPlay: 'कैसे खेलें',
  chooseMode: 'एक एडवेंचर चुनें',
  choosePlayers: 'कौन खेल रहा है?',
  spin: 'पहिया घुमाओ!',
  spinning: 'घूम रहा है…',
  getReady: 'तैयार हो जाओ',
  holdPose: 'आसन को बनाए रखो!',
  startPose: 'मैं तैयार हूँ — शुरू!',
  pass: 'शाबाश! ⭐',
  needsPractice: 'चलो अभ्यास करें 💪',
  monitorPrompt: 'बड़े: यह कैसा रहा?',
  celebrate: 'वाह!',
  encourage: 'अच्छी कोशिश — जारी रखो!',
  results: 'परिणाम',
  playAgain: 'फिर से खेलें',
  pause: 'रोकें',
  resume: 'जारी रखें',
  quit: 'खेल छोड़ें',
  leaderboard: 'लीडरबोर्ड',
  achievements: 'उपलब्धियाँ',
  statistics: 'आँकड़े',
  settings: 'सेटिंग्स',
  admin: 'बड़ों का क्षेत्र',
  poseLibrary: 'आसन संग्रह',
  players: 'खिलाड़ी',
  wheelBuilder: 'व्हील बिल्डर',
  backup: 'बैकअप और पुनर्स्थापना',
  funFact: 'मज़ेदार तथ्य',
  benefits: 'लाभ',
  safety: 'सुरक्षा पहले',
};

const TABLES = { en, hi };

export function lang() { return getSetting('lang') === 'hi' ? 'hi' : 'en'; }
export function t(key) { const table = TABLES[lang()] || en; return table[key] ?? en[key] ?? key; }
export function strings() { return TABLES[lang()] || en; }
export const LANGUAGES = [{ id: 'en', name: 'English' }, { id: 'hi', name: 'हिन्दी (Hindi)' }];
export default { t, strings, lang, LANGUAGES };
